import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AppProvider } from "@/app/context/appcontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VibeTribe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>{children}
      <Toaster position= "top-right" />
      </AppProvider>
      </body>
    </html>
  );
}
